# Generated by Django 5.2.9 on 2025-12-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='phone',
            field=models.CharField(default=1, max_length=20, verbose_name='Контактный номер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='AnnouncementImage',
        ),
    ]
